version: "3.10"

services:
  web-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - .env

    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    volumes:
      - .:/core
      - ./apps/static:/app/static
    ports:
    - "8013:8013"
    command: bash -c "python manage.py migrate && gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8013"
    environment:
      - .env
    depends_on:
      - web-db
